# Docker installation options
docker_install_from_apt: false
docker_apt_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
docker_version: "5:20.10.24~3-0~ubuntu-focal"
docker_user: "ubuntu"

# System requirements
disable_swap: true
required_packages:
  - curl
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - gnupg 
  - nfs-common