---
- name: Install Docker and dependencies
  import_tasks: setup_docker.yml
  tags: 
    - docker
    - setup

- name: Configure and run Wireguard
  import_tasks: setup_wireguard.yml
  tags:
    - wireguard
    - setup

- name: Configure peer settings
  import_tasks: configure_peers.yml
  tags:
    - wireguard
    - config 